@startuml

title UC2 - Vælg eksisterende opgave
hide footbox

<style>
element {
    BackGroundColor: #dbd7d7;
}
sequenceDiagram {
    arrow {
        FontSize: 14;
        HorizontalAlignment: center;
    }
}
</style>

actor ": Chef" as C
participant ": System" as S

C -> S: vælgEksisternedeOpgave()

S --> C: viser liste over tidligere opgaver

C -> S: vælgOpgave()

S --> C: viser medarbejderliste

C -> S: vælgMedarbejder()

C -> S: angivDeadlineogPrioritet()

C -> S: gemOpgave()

S --> C: opretter afventende opgave

S --> C: viser nyoprettet opgave

@enduml